# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 10:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niid_db', '0006_auto_20160725_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toxchar',
            name='tox_stomach',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None, verbose_name='\u041e\u0441\u0442\u0440\u0430\u044f \u0442\u043e\u043a\u0441\u0438\u0447\u043d\u043e\u0441\u0442\u044c \u043f\u0440\u0438 \u0432\u0432\u0435\u0434\u0435\u043d\u0438\u0438 \u0432 \u0436\u0435\u043b\u0443\u0434\u043e\u043a'),
        ),
    ]
