# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 16:15
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niid_db', '0012_auto_20160725_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toxchar',
            name='eyes_irritation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='\u0420\u0430\u0437\u0434\u0440\u0430\u0436.\u0434\u0435\u0439\u0441\u0442\u0432\u0438\u0435 \u043d\u0430 \u0433\u043b\u0430\u0437\u0430'),
        ),
        migrations.AlterField(
            model_name='toxchar',
            name='resorbtive_action',
            field=models.CharField(blank=True, choices=[(b'POS_MO', '\u041d\u0430\u043b\u0438\u0447\u0438\u0435 \u044d\u0444\u0444\u0435\u043a\u0442\u0430, \u043c\u044b\u0448\u0438'), (b'NEG_MO', '\u041e\u0442\u0441\u0443\u0442\u0441\u0442\u0432\u0438\u0435 \u044d\u0444\u0444\u0435\u043a\u0442\u0430, \u043c\u044b\u0448\u0438'), (b'POS_RA', '\u041d\u0430\u043b\u0438\u0447\u0438\u0435 \u044d\u0444\u0444\u0435\u043a\u0442\u0430, \u043a\u0440\u044b\u0441\u044b'), (b'NEG_RA', '\u041e\u0442\u0441\u0443\u0442\u0441\u0442\u0432\u0438\u0435 \u044d\u0444\u0444\u0435\u043a\u0442\u0430, \u043a\u0440\u044b\u0441\u044b')], max_length=6, null=True, verbose_name='\u041a\u043e\u0436\u043d\u043e-\u0440\u0435\u0437\u043e\u0440\u0431\u0442\u0438\u0432\u043d\u043e\u0435 \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u0435'),
        ),
    ]
