# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 16:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niid_db', '0013_auto_20160725_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toxchar',
            name='sensitization',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='\u0421\u0435\u043d\u0441\u0438\u0431\u0438\u043b\u0438\u0437\u0438\u0440.\u0434\u0435\u0439\u0441\u0442\u0432\u0438\u0435'),
        ),
    ]
