# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 16:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niid_db', '0014_auto_20160725_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toxchar',
            name='resorbtive_action',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='\u041a\u043e\u0436\u043d\u043e-\u0440\u0435\u0437\u043e\u0440\u0431\u0442\u0438\u0432\u043d\u043e\u0435 \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u0435'),
        ),
    ]
