# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 19:32
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niid_db', '0015_auto_20160725_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='target_objects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='\u0426\u0435\u043b\u0435\u0432\u044b\u0435 \u043e\u0431\u044a\u0435\u043a\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='tox_char',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='niid_db.ToxChar', verbose_name='\u0422\u043e\u043a\u0441\u0438\u043a\u043e\u043b\u043e\u0433\u0438\u0447\u0435\u0441\u043a\u0430\u044f \u0445\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0430'),
        ),
    ]
