# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niid_db', '0017_auto_20160725_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='enclosure',
            name='purpose',
            field=models.CharField(choices=[(b'PEOPLE', '\u041d\u0430\u0441\u0435\u043b\u0435\u043d\u0438\u0435\u043c \u0432 \u0431\u044b\u0442\u0443'), (b'PEOPLE_CHILDREN', '\u041d\u0430\u0441\u0435\u043b\u0435\u043d\u0438\u0435\u043c \u0432 \u0431\u044b\u0442\u0443, \u0432\u043a\u043b\u044e\u0447\u0430\u044f \u0434\u0435\u0442\u0435\u0439'), (b'SPECIALIST', '\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0441\u0442\u0430\u043c\u0438'), (b'SPECIALIST_PEOPLE', '\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0441\u0442\u0430\u043c\u0438 \u0438 \u043d\u0430\u0441\u0435\u043b\u0435\u043d\u0438\u0435\u043c \u0432 \u0431\u044b\u0442\u0443'), (b'SPECIALIST_PEOPLE_CHILDREN', '\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0441\u0442\u0430\u043c\u0438 \u0438 \u043d\u0430\u0441\u0435\u043b\u0435\u043d\u0438\u0435\u043c \u0432 \u0431\u044b\u0442\u0443, \u0432\u043a\u043b\u044e\u0447\u0430\u044f \u0434\u0435\u0442\u0435\u0439')], default='PEOPLE_CHILDREN', max_length=100, verbose_name='\u041d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 (\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u043e\u0442\u0440\u0435\u0431\u0438\u0442\u0435\u043b\u0435\u0439)'),
            preserve_default=False,
        ),
    ]
