# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niid_db', '0026_auto_20160730_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='toxchar',
            name='dl50_nk_value',
            field=models.FloatField(blank=True, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435 DL50 \u043d/\u043a, \u043c\u0433/\u043a\u0433'),
        ),
        migrations.AddField(
            model_name='toxchar',
            name='dl50_vz_value',
            field=models.FloatField(blank=True, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435 DL50 \u0432/\u0436, \u043c\u0433/\u043a\u0433'),
        ),
        migrations.AlterField(
            model_name='toxchar',
            name='dl50_nk',
            field=models.CharField(max_length=255, verbose_name='DL50'),
        ),
        migrations.AlterField(
            model_name='toxchar',
            name='dl50_vz',
            field=models.CharField(max_length=255, verbose_name='DL50'),
        ),
    ]
